apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: frontend
    port: 3000
    nodePort: 30004
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostname: frontend
      containers:
      - env:
        image: wesmin/frontend:presentation
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 600m
          requests:
            cpu: 400m
